{% set name = "frictionless" %}
{% set version = "5.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab4bfe55f5d831c15a16760685036fdd85c9026d2d7c633b6672b1b04f8c48c6

build:
  number: 0
  entry_points:
    - frictionless = frictionless.__main__:console
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python >=3.8
    - petl >=1.6
    - marko >=1.0
    - attrs >=22.2.0
    - jinja2 >=3.0
    - pyyaml >=5.3
    - isodate >=0.6
    - rfc3986 >=1.4
    - chardet >=3.0
    - pydantic >=2.0
    - requests >=2.10
    - humanize >=4.2
    - tabulate >=0.8.10
    - jsonschema <4.18
    - simpleeval >=0.9.11
    - stringcase >=1.2
    - typer[all] >=0.5
    - validators >=0.18
    - python-slugify >=1.2
    - python-dateutil >=2.8
    - typing-extensions >=4.3

test:
  imports:
    - frictionless
  commands:
    - frictionless --help
    - pip check
  requires:
    - pip

about:
  home: http://github.com/frictionlessdata/frictionless-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Frictionless is a framework to describe, extract, validate, and transform tabular data

extra:
  recipe-maintainers:
    - fhoehle
    - roll
