{% set name = "frictionless" %}
{% set version = "5.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 352fc84d834b85d2195813c700079472fea0e49c5938f04a3ef92dfa63ec4be0

build:
  number: 0
  entry_points:
    - frictionless = frictionless.__main__:program
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.8
    - petl >=1.6
    - marko >=1.0
    - attrs >=21.0
    - jinja2 >=3.0
    - pyyaml >=5.3
    - isodate >=0.6
    - rfc3986 >=1.4
    - chardet >=3.0
    - requests >=2.10
    - humanize >=4.2
    - tabulate >=0.8.10
    - jsonschema >=2.5
    - simpleeval >=0.9.11
    - stringcase >=1.2
    - typer[all] >=0.5
    - validators >=0.18
    - python-slugify >=1.2
    - python-dateutil >=2.8
    - typing-extensions >=4.3


test:
  imports:
    - frictionless
  commands:
    - frictionless --help
    - pip check
  requires:
    - pip

about:
  home: http://github.com/frictionlessdata/frictionless-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Frictionless is a framework to describe, extract, validate, and transform tabular data

extra:
  recipe-maintainers:
    - roll
